spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gss
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
